services:
  postgres:
    image: pgvector/pgvector:pg16
    volumes:
      - bitewise_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  django:
    build: backend
    command: ["uv", "run", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/.venv
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:dev_password@postgres:5432/postgres

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"

volumes:
  frontend_node_modules:
  bitewise_postgres:
